negotiate(6, 0xffffffff, 0xffffffff)
connect("client.example.test", "203.0.113.25")
helo("client.example.test")
mailfrom("<sender@example.test>")
rcptto("<recipient@example.test>")
data()
header("From", "sender@example.test")
header("To", "recipient@example.test")
header("Subject", "policy retry proof")
header("Message-ID", "<policy-retry-proof@example.test>")
header("Message-Instance", "1")
eoh()
body("deterministic body\r\n")
local actions = eom()
assert_replycode(actions, "451 4.7.1")
quit()
