dofile("/fixture/message.lua")
local actions = policy_e2e_message({identity = "received-dsn-proof"})
assert_final(actions, "accept")
assert_added_header(actions, "X-Spamd-Result", "DKIM2_DSN_STRUCTURE_VALID")
assert_added_header(actions, "X-Spamd-Result", "DKIM2_DSN_EMBEDDED_VERIFIED")
assert_added_header(actions, "X-Spamd-Result", "DKIM2_DSN_OUTER_ALIGNMENT_ALIGNED")
assert_added_header(actions, "X-Spamd-Result", "DKIM2_DSN_RECIPIENT_LINKAGE_LINKED")
assert_added_header(actions, "X-Spamd-Result", "DKIM2_DSN_LOCAL_HOP_LOCAL")
assert_added_header(actions, "X-Spamd-Result", "DKIM2_DSN_PROPAGATION_NOT_FAILURE")
quit()
