// Command wiregen emits the opaque JSON-string wrapper used at generated
// OpenAPI boundaries.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const generatedSource = `// Code generated by wiregen; DO NOT EDIT.

package {{PACKAGE}}

import (
	"bytes"
	"errors"
	"fmt"
	"unicode/utf16"
	"unicode/utf8"
)

const (
	maxProtectedStringBytes     = 44_739_244
	maxProtectedStringJSONBytes = 47_878_316
	protectedFormattingValue    = "<protected>"
)

var (
	errInvalidProtectedString = errors.New("invalid protected string")
	errProtectedStringTooLarge = errors.New("protected string too large")
)

// ProtectedString keeps security-sensitive request text out of default
// diagnostic formatting.
type ProtectedString struct {
	state *protectedStringState
}

type protectedStringState struct {
	value string
}

// NewProtectedString constructs a valid opaque value without normalizing its
// UTF-8 bytes.
func NewProtectedString(value string) (ProtectedString, error) {
	if !utf8.ValidString(value) {
		return ProtectedString{}, errInvalidProtectedString
	}
	if len(value) > maxProtectedStringBytes {
		return ProtectedString{}, errProtectedStringTooLarge
	}

	return ProtectedString{state: &protectedStringState{value: value}}, nil
}

// Bytes returns a byte-preserving copy for the owning transport adapter.
func (value ProtectedString) Bytes() ([]byte, error) {
	if value.state == nil {
		return nil, errInvalidProtectedString
	}

	return []byte(value.state.value), nil
}

// MarshalJSON emits the protected value only for its intended JSON transport.
func (value ProtectedString) MarshalJSON() ([]byte, error) {
	if value.state == nil {
		return nil, errInvalidProtectedString
	}

	return encodeJSONString(value.state.value)
}

// UnmarshalJSON accepts one bounded RFC 8259 string and preserves its decoded
// UTF-8 bytes without replacement or normalization.
func (value *ProtectedString) UnmarshalJSON(data []byte) error {
	if value == nil {
		return errInvalidProtectedString
	}
	value.state = nil

	decoded, err := decodeJSONString(data)
	if err != nil {
		return err
	}
	if len(decoded) > maxProtectedStringBytes {
		return errProtectedStringTooLarge
	}

	value.state = &protectedStringState{value: decoded}

	return nil
}

// String returns a content-free diagnostic representation.
func (value ProtectedString) String() string {
	return protectedFormattingValue
}

// GoString returns a content-free Go-syntax diagnostic representation.
func (value ProtectedString) GoString() string {
	return protectedFormattingValue
}

// Format makes every fmt verb content-free for valid and invalid values.
func (value ProtectedString) Format(state fmt.State, verb rune) {
	_, _ = state.Write([]byte(protectedFormattingValue))
}

// encodeJSONString deterministically escapes only bytes that RFC 8259 requires
// JSON string syntax to escape.
func encodeJSONString(value string) ([]byte, error) {
	if !utf8.ValidString(value) {
		return nil, errInvalidProtectedString
	}

	var encoded bytes.Buffer
	encoded.Grow(min(len(value)+2, maxProtectedStringJSONBytes))
	encoded.WriteByte('"')
	for _, current := range []byte(value) {
		switch current {
		case '"', '\\':
			encoded.WriteByte('\\')
			encoded.WriteByte(current)
		case '\b':
			encoded.WriteString(` + "`\\b`" + `)
		case '\f':
			encoded.WriteString(` + "`\\f`" + `)
		case '\n':
			encoded.WriteString(` + "`\\n`" + `)
		case '\r':
			encoded.WriteString(` + "`\\r`" + `)
		case '\t':
			encoded.WriteString(` + "`\\t`" + `)
		default:
			if current < 0x20 {
				const hexadecimal = "0123456789abcdef"
				encoded.WriteString(` + "`\\u00`" + `)
				encoded.WriteByte(hexadecimal[current>>4])
				encoded.WriteByte(hexadecimal[current&0x0f])
			} else {
				encoded.WriteByte(current)
			}
		}
		if encoded.Len()+1 > maxProtectedStringJSONBytes {
			return nil, errProtectedStringTooLarge
		}
	}
	encoded.WriteByte('"')

	return encoded.Bytes(), nil
}

// decodeJSONString strictly decodes one bounded RFC 8259 string.
func decodeJSONString(data []byte) (string, error) {
	if len(data) > maxProtectedStringJSONBytes {
		return "", errProtectedStringTooLarge
	}
	if len(data) < 2 || data[0] != '"' || data[len(data)-1] != '"' || !utf8.Valid(data) {
		return "", errInvalidProtectedString
	}

	var decoded bytes.Buffer
	decoded.Grow(len(data) - 2)

	for offset := 1; offset < len(data)-1; {
		current := data[offset]
		if current == '"' || current < 0x20 {
			return "", errInvalidProtectedString
		}
		if current != '\\' {
			r, width := utf8.DecodeRune(data[offset : len(data)-1])
			if r == utf8.RuneError && width == 1 {
				return "", errInvalidProtectedString
			}
			decoded.Write(data[offset : offset+width])
			offset += width
			continue
		}

		offset++
		if offset >= len(data)-1 {
			return "", errInvalidProtectedString
		}
		switch data[offset] {
		case '"', '\\', '/':
			decoded.WriteByte(data[offset])
			offset++
		case 'b':
			decoded.WriteByte('\b')
			offset++
		case 'f':
			decoded.WriteByte('\f')
			offset++
		case 'n':
			decoded.WriteByte('\n')
			offset++
		case 'r':
			decoded.WriteByte('\r')
			offset++
		case 't':
			decoded.WriteByte('\t')
			offset++
		case 'u':
			first, next, ok := decodeJSONHexRune(data, offset+1)
			if !ok {
				return "", errInvalidProtectedString
			}
			offset = next
			if utf16.IsSurrogate(first) {
				if first < 0xd800 || first > 0xdbff || offset+2 > len(data)-1 ||
					data[offset] != '\\' || data[offset+1] != 'u' {
					return "", errInvalidProtectedString
				}
				second, afterSecond, secondOK := decodeJSONHexRune(data, offset+2)
				if !secondOK || second < 0xdc00 || second > 0xdfff {
					return "", errInvalidProtectedString
				}
				first = utf16.DecodeRune(first, second)
				offset = afterSecond
			}
			decoded.WriteRune(first)
		default:
			return "", errInvalidProtectedString
		}
		if decoded.Len() > maxProtectedStringBytes {
			return "", errProtectedStringTooLarge
		}
	}

	return decoded.String(), nil
}

// decodeJSONHexRune decodes one four-digit JSON Unicode escape.
func decodeJSONHexRune(data []byte, offset int) (rune, int, bool) {
	if offset+4 > len(data)-1 {
		return 0, offset, false
	}

	var result rune
	for _, digit := range data[offset : offset+4] {
		result <<= 4
		switch {
		case digit >= '0' && digit <= '9':
			result += rune(digit - '0')
		case digit >= 'a' && digit <= 'f':
			result += rune(digit-'a') + 10
		case digit >= 'A' && digit <= 'F':
			result += rune(digit-'A') + 10
		default:
			return 0, offset, false
		}
	}

	return result, offset + 4, true
}
`

var errInvalidArguments = errors.New("invalid wire generator arguments")

// main reports generation failures without exposing generated request values.
func main() {
	if err := run(os.Args[1:]); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// run parses the bounded command surface and writes one deterministic output.
func run(arguments []string) error {
	flags := flag.NewFlagSet("wiregen", flag.ContinueOnError)
	flags.SetOutput(&bytes.Buffer{})

	var packageName string
	var outputPath string
	flags.StringVar(&packageName, "package", "", "generated Go package name")
	flags.StringVar(&outputPath, "output", "", "generated Go output path")

	if err := flags.Parse(arguments); err != nil {
		return errInvalidArguments
	}
	if flags.NArg() != 0 || outputPath == "" || !validPackageName(packageName) {
		return errInvalidArguments
	}

	source, err := render(packageName)
	if err != nil {
		return err
	}
	if err := writeFileAtomically(outputPath, source); err != nil {
		return fmt.Errorf("write generated wrapper: %w", err)
	}

	return nil
}

// validPackageName accepts only a non-keyword Go identifier.
func validPackageName(packageName string) bool {
	return token.IsIdentifier(packageName) && token.Lookup(packageName) == token.IDENT
}

// render substitutes the sole target-specific input and formats the result.
func render(packageName string) ([]byte, error) {
	if !validPackageName(packageName) {
		return nil, errInvalidArguments
	}

	source := strings.ReplaceAll(generatedSource, "{{PACKAGE}}", packageName)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format generated wrapper: %w", err)
	}

	return formatted, nil
}

// writeFileAtomically prevents a failed generation from truncating an approved
// wrapper.
func writeFileAtomically(outputPath string, source []byte) error {
	directory := filepath.Dir(outputPath)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return err
	}

	file, err := os.CreateTemp(directory, ".protected-string-*.tmp")
	if err != nil {
		return err
	}
	temporaryPath := file.Name()
	complete := false
	defer func() {
		if !complete {
			_ = os.Remove(temporaryPath)
		}
	}()

	if err := file.Chmod(0o644); err != nil {
		_ = file.Close()
		return err
	}
	if _, err := file.Write(source); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryPath, outputPath); err != nil {
		return err
	}
	complete = true

	return nil
}
